apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: webhook-receiver
  namespace: flux-system
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`flux-webhook-receiver.ops.misery.systems`)
      kind: Rule
      services:
        - name: webhook-receiver
          port: 80
  tls:
    secretName: flux-webhook-receiver-ops-misery-systems
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: flux-webhook-receiver-ops-misery-systems
  namespace: flux-system
spec:
  secretName: flux-webhook-receiver-ops-misery-systems
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - flux-webhook-receiver.ops.misery.systems
