apiVersion: v1
kind: Secret
metadata:
    name: ops-webhook-secret
    namespace: flux-system
type: Opaque
stringData:
    token: 502b2968a2ca002218b1ad492834e77e3783105a
sops:
    age:
        - recipient: age1gn9rqrgxqwkhs2ggpn6tp9yk22rtwczn2j5rxuxcrd2muea09afqnryz0y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0ckxOblVMNUFoMVBMWDVk
            TFlGQW9ZSEJsZjFrNkx6SEpOdzlRTTJxVndzCmNyZlB2NCs1VU5ESzdaQjh1YlIz
            UVQwRnVBM2Z6blNhd25rSVJPOFQ3Q0EKLS0tIEMvV3lqSzEwdFJCNW11bEQyQTFB
            MzZCb1FOSVN1L2RKUU5KOFAvcGkwUk0K6yOTpPw+xe5D/5IlewJnuwmKmVDE0uG/
            B1WJxWw6YpDpWFWXx9tXjQfXcy+iDoGMshUqEURA/KLqYseYS8H24w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-11T15:07:49Z"
    mac: ENC[AES256_GCM,data:yDYZ6LZ6fi/9d5OzlfnLz7ZzGIEQOlxKASUt1KSdHfVGB/3yesudBTYKuO1kMB0kUvlOl7+Urw9n59VI8JgeRf1QxJ2Q8Zqzt6cC7tSlt45MfBd6Ws6R8a1sO3/fU/PQFDzKUZ0s/SS9xw29DIP4t8dalvPHNgiFCFd/je/7P1w=,iv:L306W8oMsAhYL2+eV4JeYW4dDyXP63XvzevM8vLas/k=,tag:dh8DaKg4Q7Uf7CJs+BXaRQ==,type:str]
    encrypted_regex: ^(data|stringData$
    version: 3.11.0
