apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: accountabilabot-data-pvc
  namespace: accountabilabot
spec:
  storageClassName: nfs-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi