apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 13ft.yaml
  - downward.yaml
  - jellyfin.yaml
  - jellyseer.yaml
  - immich.yaml
  - ntfy.yaml
  - misery.systems.yaml
  - stocky.yaml
  - stock-corn-stats.yaml
  - elephant-shutter-upper.yaml
