apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sops-operator
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./flux/apps/sops-operator
  prune: true
  wait: true
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: sops-secrets-operator
  namespace: flux-system
spec:
  interval: 10m
  chart:
    spec:
      chart: sops-secrets-operator
      version: "0.8.0"
      sourceRef:
        kind: HelmRepository
        name: isindir
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: isindir
  namespace: flux-system
spec:
  interval: 10m
  url: https://isindir.github.io/sops-secrets-operator/