apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: stock-corn-stats
  namespace: flux-system
spec:
  interval: 1h0m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: "flux/apps/stock-corn-stats"
  prune: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age