apiVersion: v1
kind: Service
metadata:
  name: downward-example
  namespace: downward
  labels:
    app: downward-example
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: http
      protocol: TCP
  selector:
    app: downward-example
