apiVersion: v1
kind: Service
metadata:
  name: downward-example
  namespace: downward
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  selector:
    app: downward-example
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
