apiVersion: v1
kind: Secret
metadata:
    name: elephant-shutter-upper-discord-token
    namespace: elephant-shutter-upper
type: Opaque
stringData:
    DISCORD_TOKEN: ENC[AES256_GCM,data:aDfBa606eTOIwMmUa/FqZ+4gsmLFB7pS+dwqfAmpclpf7NMMi9Dxu+/XTQlw2GSNbZ+ZUy1FTmf3pp6ajzr6lVwxBChvHt7s,iv:ICOc0qF+S1AldDH2Fsd1wxc4CMeS1ytQkJMaGiYSrfI=,tag:OsUM0jp08KUkVeIDLFBmIA==,type:str]
    TARGET_USER_ID: ENC[AES256_GCM,data:7u8H++p7Bp8EJ87teE+5O8v0,iv:1UQqInC+U7o6PEURy/r8WLPgI7N5pwCh2cXsrXqsMJo=,tag:gwBqZ0xd09NNwMzJQCWXnQ==,type:int]
    BOT_OWNER_ID: ENC[AES256_GCM,data:/0kW4VCfa9ywyiF8ObTw6Mji,iv:QG4COCFFZPeBVyDUq+5ICQJ1kSfs1ga1wnsG1RZ7KeM=,tag:pAXyQ9gmCZYzxcZFDrsF8Q==,type:int]
sops:
    age:
        - recipient: age1gn9rqrgxqwkhs2ggpn6tp9yk22rtwczn2j5rxuxcrd2muea09afqnryz0y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnTFV5ay9CR1YvbnQ1TVlu
            Z3JUWHNHQUFLbExmWnZFZmRMZUdmRVRXRGo4CnVNVjkvMVBmczNYR3B6OXFKcmFu
            TjRNTmdDWGJ1MCs2Q0sxMDdsRHZ6UTAKLS0tIGk0SGJuMUQ2ajJrN0t2Y1NoM1By
            OXU4aHllaGI1Z3ZPOEtSeTlTVHNDeTAKi8fMuR7W6beBWOmSB8y3x6ypG0ivQM1t
            a4u4kjx4ts/zO5ZVfftY1+lDdU2K8kTnSLGDsRUcNMSPKbM1LBlbmw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-05T17:00:12Z"
    mac: ENC[AES256_GCM,data:WarjTPetAPJ3GKD9cZH/qStEU+c6H5Pjo0SWyHEj6MsRXHYCT6Y1AON3IPZ0kYZNAk54q1g6d6Z5WmaMVIH3EgLxkGTFH/cbXDxAZNijTMDbTjU9q++vcIVDu8B6YriwN/J8pMBrChuCMrGFm/+dwdR8wSmSOXOI9tVKwwOCjUY=,iv:/rYFqKqoPSWBvA+BOuXSt+GcH6oaynQYxRZBVL+YF6c=,tag:qGV+egv6TqlWOZooQKirTg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
