apiVersion: v1
kind: Secret
metadata:
    name: elephant-shutter-upper-discord-token
    namespace: elephant-shutter-upper
type: Opaque
stringData:
    DISCORD_TOKEN: ENC[AES256_GCM,data:EiQ8ikyRmJf+W3lN5nBFBMN4JyEH2ZkshD88PHv3AISzGHvAoAQW7RRUqcaF826hZu0GvnZG58jYHDQvY4/X0W+dCUXzvozg,iv:1xglQSJQ4O5Ir4oOt/qx5GuEcLRizyo1vyOEHpsV5pE=,tag:qxg++DeOE/zGYeLYvxfWXQ==,type:str]
    TARGET_USER_ID: ENC[AES256_GCM,data:VRnzO14a8zTJdbef7AdXRjLK,iv:rNcVSGKBBvxsiCk0Qqd9PgtYxuRle9OPTa6KGNWLlPw=,tag:YthEkyLnUPU3ywO3xRqs/Q==,type:str]
    BOT_OWNER_ID: ENC[AES256_GCM,data:t3gKkTtAdhBxAzoSNXZCH7y/,iv:0akhb1Q0/drflwmdcWCWgfJZFpkQ7pfz2Mq+/DIkgr4=,tag:xt3uQU4LQRSAF2ytL6fGLQ==,type:str]
    JACK_USER_ID: ENC[AES256_GCM,data:5NqFmvXBfkVpzquwvK0TCwpx,iv:3tdjxjeqKMLrjVk12Vc8eAEBYR+2rpxyOAd0jgc2D5g=,tag:4JDwosd7wN2Ht9OQj23Fhw==,type:str]
    OPENAI_API_KEY: ENC[AES256_GCM,data:mYgctndAyCLolngIQ98WTka25f3L3ge3mw==,iv:vhiGtVq0zqwPTTg6tjqJH89sWngji8t219HRsWkGNU4=,tag:9prDo3lv24F4pJCAAv+WuQ==,type:str]
    OPENAI_API_URL: ENC[AES256_GCM,data:JP8qECvDv6UHYd5O3OYcS4MmeD31PwOvFhYOE1bjM7rUbIk=,iv:IEy7Px6WBDmKNSV/Dg3e61Mjym4hxoI3pE0G6+THqUk=,tag:6Z1elq9RHRIwMQP083ekDQ==,type:str]
    OPENAI_MODEL: ENC[AES256_GCM,data:eLp0tIktfSsRKNM=,iv:zEW63ttetACb4IXiUGndXuminD2WUNTopzEFD3/ZqFI=,tag:c7UNu0UcIEz/AS2s6ZFacQ==,type:str]
sops:
    age:
        - recipient: age1gn9rqrgxqwkhs2ggpn6tp9yk22rtwczn2j5rxuxcrd2muea09afqnryz0y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYWlhnZ2ltTlVoY0lScG1Z
            a2EzZ2lRQldKRjI4YVhocEZlMW5hb2RFTnhZCmpzWWtISWJlcHZaYk5KZnFrL3Ev
            N1JvSk40TzhiKzNrUSs0YnIrNDF2ejQKLS0tIFJFVXRjWEplRGdRM2lYNTJtbGYz
            Y0ovZG9KeDlwSXo2RktvUVdTaE5SY1UKW9lKhIo9CQHnHu1hpEySHUit7bVJp1wu
            QcMKod7R//8GGEC9Dn8G6qoGGZqZjMTDax4humOJ/U5Tdq8uJgaGVA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-17T18:22:32Z"
    mac: ENC[AES256_GCM,data:m1ZA8YrkZtFEtAyqlgvHZwZ9VtqmbZmorotjymDngAdpCicA8Fqkiijp0PQUkpVip+OoB0y262CPE8wtf5NxhLATPiBPagfHFPofg87PlKyvgUzwCRFRg0gVmmTWSSXJya07XsavQvFk3ijuukztnpMnzfq7x1cS+/SGB9gtNh4=,iv:c6br3rbr8gZ9oGtFgPoWPCUwi8ArmFu7Al7doy8ufuw=,tag:4imyLdW+IY/M8HiVsbPDbw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
