apiVersion: v1
kind: Secret
metadata:
    name: elephant-shutter-upper-discord-token
    namespace: elephant-shutter-upper
type: Opaque
stringData:
    DISCORD_TOKEN: ENC[AES256_GCM,data:g4IglX5HBskI8jByPP+XIyt8/3blIrFNNPFduq2TvXVTrJ7yodYYLjhVVqcSDKQr/b7HYaPc0/fzXNpH3mlLx9D5ZdYxZiOE,iv:H3/vv+Jec+bleQ68xXByI8N5d2k/NBgXR1lsDQGMyFc=,tag:b1SmEG+N6ZvdMLb/uf5auw==,type:str]
    TARGET_USER_ID: ENC[AES256_GCM,data:XSgRENGKNBVHO5qWLEDSx6EU,iv:Ols25CWLL6jVHKIv6uS3ohfy4Fh9XcoKoM1ACyrbDms=,tag:uyZnr1jnPAvRpQtmI2z0Dw==,type:str]
    BOT_OWNER_ID: ENC[AES256_GCM,data:26AeNoOtdBvfgSHc2zUQx1NM,iv:J9ZcKFjTx54xS582uxsGy/h9DtPos6eqC7Ej3ll0izg=,tag:SLrnDH2BnS2HrzPtcAHUZQ==,type:str]
    JACK_USER_ID: ENC[AES256_GCM,data:lKgVGUtypYtQNsORYtecv6Zs,iv:RVFLbs6EjiEJdyX6cUSuxm1jduQGhUykLv8MYCPhCtk=,tag:UVUnhIKJYDpQ4vAnpJMoHw==,type:str]
    OPENAI_API_KEY: ENC[AES256_GCM,data:zGGOiC0w4I8xtwXqvMFiuIo/8FCsBknIXw==,iv:O446GeOBwsNAKmu75pqULd+Lh3HCu90M/Bu1ssuBRIs=,tag:2LJZA1CD/BL3ZXcrPYda2g==,type:str]
    OPENAI_API_URL: ENC[AES256_GCM,data:Ymx4xX1qiHfbzg0GOxlQAp5ZbvBevzBuYflI9LFW4GxS5Y8=,iv:JJ4rFb/coadyonC+oSJWrpSsHo7HXmR3pX1jJOSETkg=,tag:+8fojzkwi92vXaUFljt0Hg==,type:str]
    OPENAI_MODEL: ENC[AES256_GCM,data:RaW2KNkSGGbx4IHfSaQSZLhJ,iv:djqs25086sKuvb83pZClUq/vzRSuJcqk/00PIt/QEAo=,tag:eAvl5fbSwjx72CBkmgOBwQ==,type:str]
sops:
    age:
        - recipient: age1gn9rqrgxqwkhs2ggpn6tp9yk22rtwczn2j5rxuxcrd2muea09afqnryz0y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5T09ybFlSV0JxazFVbERh
            WDIyNC91bzFJdktPbnFkQWNxWU5zRUtpeEFrCjlFNFluV1JWR3dLTWlKVmd3aERW
            MjB4cVBzSjBsd216aUFnbTZ1RnJXSFkKLS0tIFpmTUZQWDVVSjF5WnNkdFhzTEJT
            RUI1cndzSWx5Vzg2ZXRmVmp1c0gvRUUKxLhp9rPMqrHnduYV9BaXvr0B1U3FdFmZ
            DhzC2PL8fjvVsY4XtR4W8ODAMvNGmeqzbrzRYgsm1PKOCullwZi8vw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-17T17:15:19Z"
    mac: ENC[AES256_GCM,data:AheCr1F6811HWp1SbvkqxxC9PGs83K1mPYM6taSSEkq15kIpOupWSGCDfFx6keWDbI8l4p1x3iCtvFLGs3tfHUZ71sJh0AyteVy/PNGEO9ED/6BMWawSuV9UB3MkPP446oufKtC+GwlDjA1j5bk6pmXXKwAUhV0RkXoLx5ISw1k=,iv:oWzREJUmRC30g58DMt0/PNqKrEd8h/Od6g+0s/6uu+I=,tag:vemrBn4o54ighGIkxhD5cw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
