{
	"data": "ENC[AES256_GCM,data:CS12uc5VVy/Aba+MeerGdjxamQAx7K1PDTnlWaUyBfHYJpERP8MXOPgK8U9PuPkvNK9lzRK8+OQzqqgmeu1GhWsM6zJEfBW5R8JxxGSXkulzlE5fWB4M9eycH8ieqC4cVr+cpQ2INg/MGvkNmpi7SnhRQ0qG4decXFm0UmVwN4lYiuz7qsbi1NmfvPGgtWQqgug9eVWfo8nsZfcfru0Aq/roPIMR/VZAeDK0mscFQtrwZai88yvZtw+epToa0iAg31OBoB0lGHDOmg==,iv:CyYOPMe99JJ9RWx1c0L94O+ekyTmBUjNtWQod+MRUyU=,tag:hyWQ431ptHgCRObOPJaFOw==,type:str]",
	"sops": {
		"age": [
			{
				"recipient": "age1gn9rqrgxqwkhs2ggpn6tp9yk22rtwczn2j5rxuxcrd2muea09afqnryz0y",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBabVJLaEV5WDc2WHNHcmcv\nek5wMWVoc3NUNlVpZkpBMG5rU1ZCSTh1Smo4CjNSODNKSHdKby9BK28vczlySFNn\nME1aNlp3cWN6bGEyMVlFVDNzVjcwaEkKLS0tIFZDYzliczRyUEI3RTdyRHFWczg4\nTlhPRUM1NGNVdlRmVFQvbThUWTY4Y0kKTf1y4CR3QHLplJsPr12R3BnNmI6YVpoA\nLs1x+GMD0C4TohmGmPwFQw0p8yprDzdJnLqRNm2fclbC5aTACbCL1A==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2025-10-05T16:35:05Z",
		"mac": "ENC[AES256_GCM,data:s6L6ulJ/BJd9aVJ9eWyRrnMIxkq/iVCjHJHjq7yqmKV/0LeNTUdmBH+9gLw9cLu27zYfM/crL5s58yvEKYFvrjMSKPXfEOSAV4d/z8Hieu0cSpMhT91HimNvgxi+hFIyTINLwvz8KdW0c/NxKxR0P/sB9N0LRrLeJKLPUlksteM=,iv:FGeXQGoaYXolUr5vZseQAuj2WqLw/lGpla8NxQRJ60k=,tag:kb426eOb9wVxB5hx76FV9g==,type:str]",
		"version": "3.11.0"
	}
}
