apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: default
spec:
  type: LoadBalancer
  ports:
    - name: web
      port: 80
      targetPort: web
      nodePort: 30090
    - name: admin
      port: 8080
      targetPort: admin
      nodePort: 30091
  selector:
    app: traefik
