apiVersion: v1
kind: Secret
metadata:
    name: stocky-discord-token
    namespace: stocky
type: Opaque
stringData:
    DISCORD_TOKEN: ENC[AES256_GCM,data:OVNenFUJ7A6m5dhhoP86gMznguCe9Wr+zyaonDQX+Rjx7cKjf2hvWt7n/6zmAVUBWPXWyFeQcQykaqnSdqdLoSDsxUC8DJEH,iv:iFoivOte2U27rh9nru3QPZ6tlERLxqAj7nQbyy9AtDo=,tag:AmAsmiymw5HTRm/wGHwFXQ==,type:str]
sops:
    age:
        - recipient: age1gn9rqrgxqwkhs2ggpn6tp9yk22rtwczn2j5rxuxcrd2muea09afqnryz0y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNai9HZGhxcEpHTDg2bERq
            ampzQmtBbm13U1VlK0lQUHNLOE51YklSa1ZVCko1V2Y0c2ZvamI1OWVWS0lweWdZ
            bEw5Z2YrVk0rODJRd24rbDJQS2RGMzQKLS0tIGV6aGNqVGljb2ZMaTZKNjB4dnBE
            Z3FZOFFEU1F1b2xzNmMwelI5ZnllZEEK16J0/mW4VGWreVeyl7z9frhNGSzHUMtS
            +Cjc+xsJA4vLD7BN4Erlsi/fjb4WN5lsJLWMtjpOjeog9pumdbKMvg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-09T23:22:55Z"
    mac: ENC[AES256_GCM,data:X82RcgyiwvhiohkWi78daXPdELWTAlUv9bcHP846H/LrDGkQZZ9EQe6a3zwZGb78MNkKh7OVBpXk2uKHCjs2bRNsdNAk3wqW9VPRE151MpmBpYN39qXspXpMViVSSSAGQo4s0t7YWnihs1GpbRwwmABZtj6eCPv6VuZX1dUOoxg=,iv:b3AkBuC2Oevbp8+NDIZgP76U0BLQNSQBJqeCUmtLHxA=,tag:xjLTVcZ2+/NsqRUZYWiiIQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
