apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: thirteenft
  namespace: thirteenft
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`13ft.misery.systems`)
      kind: Rule
      services:
        - name: thirteenft
          port: 5000
  tls:
    secretName: thirteenft-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: thirteenft-tls
  namespace: thirteenft
spec:
  secretName: thirteenft-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
    - 13ft.misery.systems
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: thirteenft
  namespace: thirteenft
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"
spec:
  ingressClassName: "traefik"
  tls:
    - hosts:
        - 13ft.misery.systems
      secretName: thirteenft-tls
  rules:
    - host: 13ft.misery.systems
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: thirteenft
                port:
                  number: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: thirteenft
  namespace: thirteenft
spec:
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: thirteenft
