apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: thirteenft
  namespace: thirteenft
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`13ft.misery.systems`)
      kind: Rule
      services:
        - name: thirteenft
          port: 5000
  tls:
    secretName: thirteenft-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: thirteenft-tls
  namespace: thirteenft
spec:
  secretName: thirteenft-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
    - 13ft.misery.systems
---
apiVersion: v1
kind: Service
metadata:
  name: thirteenft
  namespace: thirteenft
spec:
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: thirteenft
