apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: downward-example
  namespace: default
spec:
  selector:
    matchLabels:
      app: downward-example
  template:
    metadata:
      labels:
        app: downward-example
    spec:
      containers:
        - name: downward-example
          image: ghcr.io/alexgaudon/downward-api:491f69c594d0c2fd5d471fd3aed3ae84c0bdea3b
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: SERVICE_ACCOUNT
              valueFrom:
                fieldRef:
                  fieldPath: spec.serviceAccountName
          # Health checks
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          # Resource limits and requests
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          # Timeout settings
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sleep", "5"]
