apiVersion: v1
kind: Service
metadata:
  name: downward-example
  namespace: default
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "60"
spec:
  selector:
    app: downward-example
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
