apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ntfy
  namespace: ntfy
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`ntfy.misery.systems`)
      kind: Rule
      services:
        - name: ntfy
          port: 80
  tls:
    secretName: ntfy-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ntfy-tls
  namespace: ntfy
spec:
  secretName: ntfy-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
    - ntfy.misery.systems
