apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ntfy-data-pvc
  namespace: ntfy
spec:
  storageClassName: nfs-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi