apiVersion: v1
kind: Endpoints
metadata:
  name: jellyfin
  namespace: jellyfin-proxy
subsets:
  - addresses:
      - ip: 10.0.0.5
    ports:
      - name: http
        port: 8096
        protocol: TCP
