apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lootsheet-pb-data-pvc
  namespace: lootsheet
spec:
  storageClassName: nfs-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

